// Script to generate daynight-map.ts from an equirectangular Earth image
// Usage: npx ts-node scripts/generate-daynight-map.ts <path-to-earth-image>
//
// Expects a NASA Blue Marble or similar equirectangular projection image.
// Resizes to 64x64 and encodes as base64 RGB888.

import sharp from 'sharp';
import fs from 'fs';
import path from 'path';

async function main() {
  const inputPath = process.argv[2];
  if (!inputPath) {
    console.error('Usage: npx ts-node scripts/generate-daynight-map.ts <earth-image-path>');
    process.exit(1);
  }

  console.log(`Processing: ${inputPath}`);

  const rgbBuffer = await sharp(inputPath)
    .resize(64, 64, { fit: 'fill' })
    .removeAlpha()
    .raw()
    .toBuffer();

  console.log(`Raw buffer size: ${rgbBuffer.length} bytes (expected 12288)`);

  const base64 = rgbBuffer.toString('base64');

  const outputPath = path.join(__dirname, '..', 'src', 'faces', 'daynight-map.ts');
  const content = `// Auto-generated Earth map data (64x64 RGB888)
// Source: equirectangular projection, resized to 64x64
// Generated by: scripts/generate-daynight-map.ts

const EARTH_MAP_BASE64 = '${base64}';

let cachedBuffer: Buffer | null = null;

export function getEarthMapBuffer(): Buffer {
  if (!cachedBuffer) {
    cachedBuffer = Buffer.from(EARTH_MAP_BASE64, 'base64');
  }
  return cachedBuffer;
}
`;

  fs.writeFileSync(outputPath, content, 'utf-8');
  console.log(`Written to: ${outputPath}`);
  console.log(`Base64 length: ${base64.length} chars`);
}

main().catch(console.error);
